import type { RewardItem } from '../types/index.ts'

export const rewardItems: RewardItem[] = [
  {
    id: 'sword-basic',
    name: 'ひのきのつるぎ',
    category: 'weapon',
    unlockCost: 100,
    description: '木でできた剣。でも立派！',
    attackStyle: {
      type: 'fire',
      color: '#ff8c00',
      glowColor: 'rgba(255, 140, 0, 0.5)',
      width: 5,
      label: '炎の一撃',
    },
  },
  {
    id: 'sword-iron',
    name: 'てつのつるぎ',
    category: 'weapon',
    unlockCost: 300,
    description: '鉄製の剣。ゾンビに有効！',
    attackStyle: {
      type: 'fire',
      color: '#ff4500',
      glowColor: 'rgba(255, 69, 0, 0.5)',
      width: 6,
      label: '烈火',
    },
  },
  {
    id: 'sword-pixel',
    name: 'ピクセルブレード',
    category: 'weapon',
    unlockCost: 600,
    description: '8ビットの世界から来た剣。',
    attackStyle: {
      type: 'magic',
      color: '#aa44ff',
      glowColor: 'rgba(170, 68, 255, 0.5)',
      width: 5,
      label: '8ビット光線',
    },
  },
  {
    id: 'armor-cloth',
    name: 'ぬののよろい',
    category: 'armor',
    unlockCost: 80,
    description: '軽くて動きやすい。ゾンビが少しのんびりになる。',
    zombieModifier: { speedMultiplier: 0.88, retreatBonus: 0, wordRetreatBonus: 0 },
  },
  {
    id: 'armor-leather',
    name: 'かわのよろい',
    category: 'armor',
    unlockCost: 250,
    description: 'ゾンビの歩みをはっきり遅らせる。',
    zombieModifier: { speedMultiplier: 0.78, retreatBonus: 0, wordRetreatBonus: 0 },
  },
  {
    id: 'armor-steel',
    name: 'はがねのよろい',
    category: 'armor',
    unlockCost: 500,
    description: 'ゾンビがかなり遭くなる。',
    zombieModifier: { speedMultiplier: 0.68, retreatBonus: 0, wordRetreatBonus: 0 },
  },
  {
    id: 'friend-slime',
    name: 'スライム',
    category: 'friend',
    unlockCost: 150,
    description: 'なかまになってくれた。正解ごとにゾンビを少し押す。',
    zombieModifier: { speedMultiplier: 1.0, retreatBonus: 0.008, wordRetreatBonus: 0 },
  },
  {
    id: 'friend-cat',
    name: 'ねこ',
    category: 'friend',
    unlockCost: 400,
    description: 'ゾンビを見張ってくれる。単語完成で大きく押す。',
    zombieModifier: { speedMultiplier: 1.0, retreatBonus: 0.015, wordRetreatBonus: 0.03 },
  },
  {
    id: 'costume-ghost',
    name: 'おばけコスチューム',
    category: 'costume',
    unlockCost: 200,
    description: 'ゾンビがびっくり！速度が落ちて後退も増える。',
    zombieModifier: { speedMultiplier: 0.92, retreatBonus: 0.010, wordRetreatBonus: 0 },
  },
  {
    id: 'bg-forest',
    name: 'もりのせかい',
    category: 'background',
    unlockCost: 350,
    description: '緑のもりでタイピング。',
  },
]
