import type { StageDefinition } from '../types/index.ts'

export const stageDefinitions: StageDefinition[] = [
  {
    id: 'lv-1-home-position',
    level: 1,
    title: 'Lv.1 ホームポジション',
    description: 'asdf jkl; を中心に、正確さを最優先で練習します。',
    inputMode: 'direct',
    targetCharsPerMinute: null,
    zombieSpeed: 'slow',
    estimatedSeconds: 120,
    prompts: [
      { id: 'lv1-01', label: 'asdf', expected: 'asdf' },
      { id: 'lv1-02', label: 'jkl;', expected: 'jkl;' },
      { id: 'lv1-03', label: 'ffjj', expected: 'ffjj' },
      { id: 'lv1-04', label: 'dkdk', expected: 'dkdk' },
      { id: 'lv1-05', label: 'slsl', expected: 'slsl' },
      { id: 'lv1-06', label: 'asdf jkl;', expected: 'asdf jkl;' },
      { id: 'lv1-07', label: 'fdsa lkj;', expected: 'fdsa lkj;' },
      { id: 'lv1-08', label: 'asdfjkl;', expected: 'asdfjkl;' },
      { id: 'lv1-09', label: 'asdfg hjkl;', expected: 'asdfg hjkl;' },
      { id: 'lv1-10', label: 'fds fds fds', expected: 'fds fds fds' },
      { id: 'lv1-11', label: 'jkl jkl jkl', expected: 'jkl jkl jkl' },
      { id: 'lv1-12', label: 'fj fj fj', expected: 'fj fj fj' },
      { id: 'lv1-13', label: 'dk dk dk', expected: 'dk dk dk' },
      { id: 'lv1-14', label: 'ask', expected: 'ask' },
      { id: 'lv1-15', label: 'sad', expected: 'sad' },
      { id: 'lv1-16', label: 'fall', expected: 'fall' },
      { id: 'lv1-17', label: 'flask', expected: 'flask' },
      { id: 'lv1-18', label: 'glad', expected: 'glad' },
      { id: 'lv1-19', label: 'half', expected: 'half' },
      { id: 'lv1-20', label: 'flag', expected: 'flag' },
    ],
  },
  {
    id: 'lv-2-alphabet',
    level: 2,
    title: 'Lv.2 アルファベット全体',
    description: 'a〜z と短い英単語を練習します。',
    inputMode: 'direct',
    targetCharsPerMinute: 20,
    zombieSpeed: 'slow',
    estimatedSeconds: 90,
    prompts: [
      { id: 'lv2-01', label: 'cat', expected: 'cat' },
      { id: 'lv2-02', label: 'dog', expected: 'dog' },
      { id: 'lv2-03', label: 'run', expected: 'run' },
      { id: 'lv2-04', label: 'hot', expected: 'hot' },
      { id: 'lv2-05', label: 'big', expected: 'big' },
      { id: 'lv2-06', label: 'yes', expected: 'yes' },
      { id: 'lv2-07', label: 'sky', expected: 'sky' },
      { id: 'lv2-08', label: 'cup', expected: 'cup' },
      { id: 'lv2-09', label: 'map', expected: 'map' },
      { id: 'lv2-10', label: 'pen', expected: 'pen' },
      { id: 'lv2-11', label: 'box', expected: 'box' },
      { id: 'lv2-12', label: 'fun', expected: 'fun' },
      { id: 'lv2-13', label: 'zip', expected: 'zip' },
      { id: 'lv2-14', label: 'jump', expected: 'jump' },
      { id: 'lv2-15', label: 'type', expected: 'type' },
      { id: 'lv2-16', label: 'game', expected: 'game' },
      { id: 'lv2-17', label: 'hero', expected: 'hero' },
      { id: 'lv2-18', label: 'code', expected: 'code' },
      { id: 'lv2-19', label: 'bird', expected: 'bird' },
      { id: 'lv2-20', label: 'wolf', expected: 'wolf' },
    ],
  },
  {
    id: 'lv-3-romaji-basic',
    level: 3,
    title: 'Lv.3 ローマ字基本',
    description: 'あ〜お行・か行・さ行・た行・な行の文字を使ったローマ字入力を練習します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 25,
    zombieSpeed: 'normal',
    estimatedSeconds: 90,
    prompts: [
      { id: 'lv3-01', label: 'あか', expected: 'あか' },
      { id: 'lv3-02', label: 'かさ', expected: 'かさ' },
      { id: 'lv3-03', label: 'さかな', expected: 'さかな' },
      { id: 'lv3-04', label: 'たこ', expected: 'たこ' },
      { id: 'lv3-05', label: 'なに', expected: 'なに' },
      { id: 'lv3-06', label: 'うた', expected: 'うた' },
      { id: 'lv3-07', label: 'きく', expected: 'きく' },
      { id: 'lv3-08', label: 'ねこ', expected: 'ねこ' },
      { id: 'lv3-09', label: 'なつ', expected: 'なつ' },
      { id: 'lv3-10', label: 'かき', expected: 'かき' },
      { id: 'lv3-11', label: 'くに', expected: 'くに' },
      { id: 'lv3-12', label: 'そこ', expected: 'そこ' },
      { id: 'lv3-13', label: 'うち', expected: 'うち' },
      { id: 'lv3-14', label: 'すし', expected: 'すし' },
      { id: 'lv3-15', label: 'あき', expected: 'あき' },
      { id: 'lv3-16', label: 'にく', expected: 'にく' },
      { id: 'lv3-17', label: 'せかい', expected: 'せかい' },
      { id: 'lv3-18', label: 'ことし', expected: 'ことし' },
      { id: 'lv3-19', label: 'たぬき', expected: 'たぬき' },
      { id: 'lv3-20', label: 'さつき', expected: 'さつき' },
    ],
  },
  {
    id: 'lv-4-romaji-advanced',
    level: 4,
    title: 'Lv.4 ローマ字応用',
    description: '濁音・促音・拗音を含む単語を練習します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 30,
    zombieSpeed: 'normal',
    estimatedSeconds: 120,
    prompts: [
      { id: 'lv4-01', label: 'しゃしん', expected: 'しゃしん' },
      { id: 'lv4-02', label: 'きって', expected: 'きって' },
      { id: 'lv4-03', label: 'じゅぎょう', expected: 'じゅぎょう' },
      { id: 'lv4-04', label: 'びっくり', expected: 'びっくり' },
      { id: 'lv4-05', label: 'きょねん', expected: 'きょねん' },
      { id: 'lv4-06', label: 'でんしゃ', expected: 'でんしゃ' },
      { id: 'lv4-07', label: 'がっこう', expected: 'がっこう' },
      { id: 'lv4-08', label: 'ざっし', expected: 'ざっし' },
      { id: 'lv4-09', label: 'どうぶつ', expected: 'どうぶつ' },
      { id: 'lv4-10', label: 'おちゃ', expected: 'おちゃ' },
      { id: 'lv4-11', label: 'びょういん', expected: 'びょういん' },
      { id: 'lv4-12', label: 'ちゃわん', expected: 'ちゃわん' },
      { id: 'lv4-13', label: 'きゅうり', expected: 'きゅうり' },
      { id: 'lv4-14', label: 'ぎゅうにゅう', expected: 'ぎゅうにゅう' },
      { id: 'lv4-15', label: 'じゃがいも', expected: 'じゃがいも' },
      { id: 'lv4-16', label: 'ちょうちょ', expected: 'ちょうちょ' },
    ],
  },
  {
    id: 'lv-5-words',
    level: 5,
    title: 'Lv.5 単語',
    description: '小学生が日常で使う身近なひらがな単語をテンポよく入力します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 35,
    zombieSpeed: 'fast',
    estimatedSeconds: 120,
    prompts: [
      { id: 'lv5-01', label: 'ともだち', expected: 'ともだち' },
      { id: 'lv5-02', label: 'がっこう', expected: 'がっこう' },
      { id: 'lv5-03', label: 'きょうりゅう', expected: 'きょうりゅう' },
      { id: 'lv5-04', label: 'すいぞくかん', expected: 'すいぞくかん' },
      { id: 'lv5-05', label: 'でんしゃ', expected: 'でんしゃ' },
      { id: 'lv5-06', label: 'おかあさん', expected: 'おかあさん' },
      { id: 'lv5-07', label: 'たんじょうび', expected: 'たんじょうび' },
      { id: 'lv5-08', label: 'べんきょう', expected: 'べんきょう' },
      { id: 'lv5-09', label: 'やきゅう', expected: 'やきゅう' },
      { id: 'lv5-10', label: 'なつやすみ', expected: 'なつやすみ' },
      { id: 'lv5-11', label: 'じてんしゃ', expected: 'じてんしゃ' },
      { id: 'lv5-12', label: 'どうぶつえん', expected: 'どうぶつえん' },
      { id: 'lv5-13', label: 'しょうがっこう', expected: 'しょうがっこう' },
      { id: 'lv5-14', label: 'りんご', expected: 'りんご' },
      { id: 'lv5-15', label: 'おにごっこ', expected: 'おにごっこ' },
    ],
  },
  {
    id: 'lv-6-short-sentences',
    level: 6,
    title: 'Lv.6 短文',
    description: '短い日本語の文をリズムよく入力します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 40,
    zombieSpeed: 'fast',
    estimatedSeconds: 180,
    prompts: [
      { id: 'lv6-01', label: 'きょうは いいてんき。', expected: 'きょうは いいてんき。' },
      { id: 'lv6-02', label: 'ぼくは げーむが すき。', expected: 'ぼくは げーむが すき。' },
      { id: 'lv6-03', label: 'たのしく べんきょう しよう！', expected: 'たのしく べんきょう しよう！' },
      { id: 'lv6-04', label: 'まいにち れんしゅう しよう。', expected: 'まいにち れんしゅう しよう。' },
      { id: 'lv6-05', label: 'がんばれ！もうすこし！', expected: 'がんばれ！もうすこし！' },
      { id: 'lv6-06', label: 'ゾンビを たおせ！', expected: 'ぞんびを たおせ！' },
      { id: 'lv6-07', label: 'ともだちと あそぶのが すき。', expected: 'ともだちと あそぶのが すき。' },
      { id: 'lv6-08', label: 'きょうも よくできました！', expected: 'きょうも よくできました！' },
      { id: 'lv6-09', label: 'おなかが すいた。ごはん たべよう。', expected: 'おなかが すいた。ごはん たべよう。' },
      { id: 'lv6-10', label: 'あしたも がんばろう！', expected: 'あしたも がんばろう！' },
      { id: 'lv6-11', label: 'いちにち いっぽずつ すすもう。', expected: 'いちにち いっぽずつ すすもう。' },
      { id: 'lv6-12', label: 'タイピングが うまく なった！', expected: 'たいぴんぐが うまく なった！' },
      { id: 'lv6-13', label: 'まちがえても だいじょうぶ。', expected: 'まちがえても だいじょうぶ。' },
      { id: 'lv6-14', label: 'もう いっかい チャレンジ！', expected: 'もう いっかい ちゃれんじ！' },
      { id: 'lv6-15', label: 'がっこうの べんきょうも がんばろう。', expected: 'がっこうの べんきょうも がんばろう。' },
      { id: 'lv6-16', label: 'はやく うてば ゾンビは にげる。', expected: 'はやく うてば ぞんびは にげる。' },
    ],
  },
  {
    id: 'lv-7-free-input',
    level: 7,
    title: 'Lv.7 自由入力',
    description: '今日の一言や日記を自由に入力します。',
    inputMode: 'free',
    targetCharsPerMinute: null,
    zombieSpeed: 'none',
    estimatedSeconds: 300,
    prompts: [{ id: 'lv7-1', label: 'きょうの ひとこと', expected: '' }],
  },
]
