import type { StageDefinition } from '../types/index.ts'

export const stageDefinitions: StageDefinition[] = [
  {
    id: 'lv-1-home-position',
    level: 1,
    title: 'Lv.1 ホームポジション',
    description: 'asdf jkl; を中心に、正確さを最優先で練習します。',
    inputMode: 'direct',
    targetCharsPerMinute: null,
    zombieSpeed: 'slow',
    estimatedSeconds: 45,
    prompts: [
      { id: 'lv1-1', label: 'asdf', expected: 'asdf' },
      { id: 'lv1-2', label: 'jkl;', expected: 'jkl;' },
      { id: 'lv1-3', label: 'asdf jkl;', expected: 'asdf jkl;' },
    ],
  },
  {
    id: 'lv-2-alphabet',
    level: 2,
    title: 'Lv.2 アルファベット全体',
    description: 'a〜z と短い英単語を練習します。',
    inputMode: 'direct',
    targetCharsPerMinute: 20,
    zombieSpeed: 'slow',
    estimatedSeconds: 60,
    prompts: [
      { id: 'lv2-1', label: 'cat', expected: 'cat' },
      { id: 'lv2-2', label: 'dog', expected: 'dog' },
      { id: 'lv2-3', label: 'zombie', expected: 'zombie' },
    ],
  },
  {
    id: 'lv-3-romaji-basic',
    level: 3,
    title: 'Lv.3 ローマ字基本',
    description: 'あ〜お行・濁音なしのローマ字入力を練習します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 25,
    zombieSpeed: 'normal',
    estimatedSeconds: 60,
    prompts: [
      { id: 'lv3-1', label: 'あおい', expected: 'あおい' },
      { id: 'lv3-2', label: 'かさ', expected: 'かさ' },
      { id: 'lv3-3', label: 'さかな', expected: 'さかな' },
    ],
  },
  {
    id: 'lv-4-romaji-advanced',
    level: 4,
    title: 'Lv.4 ローマ字応用',
    description: '濁音・促音・拗音を練習します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 30,
    zombieSpeed: 'normal',
    estimatedSeconds: 60,
    prompts: [
      { id: 'lv4-1', label: 'しゃしん', expected: 'しゃしん' },
      { id: 'lv4-2', label: 'きって', expected: 'きって' },
      { id: 'lv4-3', label: 'じゅぎょう', expected: 'じゅぎょう' },
    ],
  },
  {
    id: 'lv-5-words',
    level: 5,
    title: 'Lv.5 単語',
    description: '身近なひらがな単語をテンポよく入力します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 35,
    zombieSpeed: 'fast',
    estimatedSeconds: 60,
    prompts: [
      { id: 'lv5-1', label: 'ともだち', expected: 'ともだち' },
      { id: 'lv5-2', label: 'がっこう', expected: 'がっこう' },
      { id: 'lv5-3', label: 'きょうりゅう', expected: 'きょうりゅう' },
    ],
  },
  {
    id: 'lv-6-short-sentences',
    level: 6,
    title: 'Lv.6 短文',
    description: '2〜3文の短い文章を練習します。',
    inputMode: 'romaji',
    targetCharsPerMinute: 40,
    zombieSpeed: 'fast',
    estimatedSeconds: 60,
    prompts: [
      { id: 'lv6-1', label: 'きょうは いいてんき。', expected: 'きょうは いいてんき。' },
      { id: 'lv6-2', label: 'ぼくは げーむが すき。', expected: 'ぼくは げーむが すき。' },
    ],
  },
  {
    id: 'lv-7-free-input',
    level: 7,
    title: 'Lv.7 自由入力',
    description: '今日の一言や日記を自由に入力します。',
    inputMode: 'free',
    targetCharsPerMinute: null,
    zombieSpeed: 'none',
    estimatedSeconds: 300,
    prompts: [{ id: 'lv7-1', label: 'きょうの ひとこと', expected: '' }],
  },
]
